### PR TITLE
version updated

### PR DESCRIPTION
**Pull request by cybinon**
Hello. I updated your project. 

- Firebase updated
- Agora updated
- Pull to refresh updated

Now it will work well. And added Requirement into to README

### CODE REVIEW

**Comment by 3NaNa7** [comment]
> Hello. I updated your project.
> 
>     * Firebase updated
> 
>     * Agora updated
> 
>     * Pull to refresh updated
> 
> 
> Now it will work well. And added Requirement into to README

@cybinon can I please get the updated version. If you could have it a private repo and give me access. I'm using it as my final year project so kindly assist. Code Owner hasn't merged yet.

**Comment by cybinon** [comment]
@samuelson-acheampong  I don't have a private repository, but I was doing some research on a voice chat app called "Audio Streaming". While looking into it, I stumbled upon a project that had many outdated version codes. I realized that there was a lot of work that needed to be done to improve it. So, I decided to update the packages to make them work better and easier for people to use someday.
If you're interested, I can give you an updated version of the app in the form of an Android apk or App bundle.

Note: Currently, there seems to be a bug in the phone authentication country code. If the owner of the project is interested, I am ready to continue the development process.

**Comment by 3NaNa7** [comment]
@cybinon I appreciate. Unfortunately, I'm a beginner. Don't know how to work with android. Flutter is the only framework I know for mobile apps. I was considering how I could get the updated files forgetting I could just diff manually. Or is there a way to get your versions of the files. I'm new to this Open Source thing.

Edited: 
I could just fork your version of the project right?

**Comment by cybinon** [comment]
Oh, I got it. I just misunderstood.

It is my forked version https://github.com/cybinon/clubhouse feel free to clone and check it.

**Comment by 3NaNa7** [comment]
Yeah, did that. Thank you. Would be glad to collaborate with you during my project process.

**Pull request closed without merging**
